### ISSUE TITLE
Unable to remove or delete a team

### ISSUE THREAD

**Issue by erae** [zpurcey/new-teamtemp#3]
I'm unable to remove or delete a team once added - the only way I could find to do so was directly in the database.

**Comment by zpurcey** [comment]
Once authenticated replace the 'admin' with the word 'set' in the url when viewing the admin page.  This will open an undocumented settings page where I've thrown a very crude hack to do a few admin tasks that would have otherwise required db changes.

It allows a team name change and if the new team name field is empty it will delete the team records.

This settings page is more accessible once you activate the automatic/scheduled archive function - a link to the settings page is added to the admin page to allow users to configure the archive frequency. All functions are more tested now so the settings page should really just be linked from the admin page permanently.

**Comment by erae** [comment]
Thanks! I like this secret feature - does what I needed.
